### PR TITLE
Fix datetime printing issue

### LINKED ISSUE #132: as_ascii table does not handle NA values in some cases.
```
library(diffdf)
library(tibble)

d1 <- tibble(
  id = c(1, 2),
  dt1 = lubridate::ymd_hms(
    "2024-01-10 01-02-03",
    "2024-01-24 14-12-49"
  )
)
d2 <- tibble(
  id = c(1, 2),
  dt1 = lubridate::ymd_hms(
    "2024-01-10 01-02-03",
    NA
  )
)

diffdf(d1, d2, "id", file = "comparison.lst")
```

Causes `as_ascii_table` to error, in particular https://github.com/gowerc/diffdf/blob/master/R/ascii_tables.R#L89 returns NA_real which then causes https://github.com/gowerc/diffdf/blob/master/R/ascii_tables.R#L93 to error

### PR DESCRIPTION
**Pull request by gowerc**
Closes #132

### CODE REVIEW

File: tests/testthat/test-miscellaneous.R [hunk 1]
```diff
@@ -252,3 +252,45 @@ test_that("datetimes compare as expected", {
...
+    d1 <- tibble(
+        id = c(1, 2),
+        dt1 = lubridate::ymd_hms(
+            "2024-01-10 01-02-03",
+            "2024-01-24 14-12-49"
+        )
+    )
+
+    d2 <- tibble(
+        id = c(1, NA),
```
Comment (kieranjmartin) [inline tests/testthat/test-miscellaneous.R:269]: is there a reason you also set id to NA here?

File: tests/testthat/test-miscellaneous.R [hunk 2]
```diff
@@ -252,3 +252,45 @@ test_that("datetimes compare as expected", {
...
+test_that("`as_ascii_table() can handle missing dates (#132)", {
+    d1 <- tibble(
+        id = c(1, 2),
+        dt1 = lubridate::ymd(
+            "2024-01-10",
+            "2024-01-24"
+        )
+    )
+
+    d2 <- tibble(
```
Comment (kieranjmartin) [inline tests/testthat/test-miscellaneous.R:288]: could we extend the test with the following cases

1) all missing dates
2) a slightly longer vector

Just to ensure full coverage of the error

**Review by kieranjmartin — CHANGES_REQUESTED** [review]
minor changes, just to expand the testing a little to ensure we have coverage

**Review by kieranjmartin — APPROVED** [review]

**Comment by gowerc** [comment]
@bundfussr - This is now on CRAN

**Comment by bundfussr** [comment]
> @bundfussr - This is now on CRAN

Great, thanks!
