### PR TITLE
Make Whitespace differences more visually identifiable

### LINKED ISSUE #87: issues with white space and new lines
Two issues here (perhaps need a separate ticket)

- The reporting off diffdf gets semi broken if a string contains a new line character
- Theres no indication for white space so you can't really tell why `" "` is being considered different to `"      "`

```
> x[5, "SRDET1"]
# A tibble: 1 × 1
  SRDET1                                                           
  <chr>                                                            
1 "FIVER WITOUT OTHER SYMPTOM. \r\nDEXA 10MG BID IV ADMINISTERED. "
> x_py[5, "SRDET1"]
# A tibble: 1 × 1
  SRDET1                                                          
  <chr>                                                           
1 "FIVER WITOUT OTHER SYMPTOM. \r\nDEXA 10MG BID IV ADMINISTERED."
```

In the diffdf report this isn't clear at all:

```
  ===============================================================================================
   VARIABLE  ..ROWNUMBER..                BASE                              COMPARE              
  -----------------------------------------------------------------------------------------------
    SRDET1         5        FIVER WITOUT OTHER SYMPTOM. 
...  FIVER WITOUT OTHER SYMPTOM. 
... 
  -----------------------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by gowerc**
Closes #87

### CODE REVIEW

File: R/ascii_tables.R [hunk 1]
```diff
@@ -108,38 +112,87 @@ as_ascii_table <- function(dat, line_prefix = "  ") {
...
+        x,
+        function(x) {
+            if (is.numeric(x)) {
+                return(as_fmt_char(x))
+            }
+            if (is.character(x) & length(x) == 1) {
+                return(as_fmt_char(x))
+            }
+            as_fmt_char(
+                paste(capture.output(dput(x)), collapse = " "),
```
Comment (kieranjmartin) [inline R/ascii_tables.R:161]: a thought, we could use https://cynkra.github.io/constructive/ which I saw at UseR. The main reason this occurs to me is the odd look of the iris dataset. Perhaps unecessary as we maybe just should expect a printed data frame to look weird, but might be worth trying?

**Review by kieranjmartin — APPROVED** [review]
